# Generated by Django 3.0 on 2021-06-10 07:09

import django.db.models.deletion
from django.db import migrations, models

import cmsplus.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cmsplus', '0005_slidepluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, editable=False, null=True, storage=cmsplus.models.SCSSStorage(), upload_to='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site Style',
                'verbose_name_plural': 'Site Styles',
                'ordering': ['order'],
            },
        ),
    ]
