# Generated by Django 2.2.11 on 2020-03-19 06:49

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_plus_pluspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('json', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='ExamplePlugin',
        ),
    ]
