# Generated by Django 2.2.11 on 2020-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_plus', '0003_auto_20200319_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plusplugin',
            old_name='json',
            new_name='_json',
        ),
    ]
